// JNT AI Assistant — rule-based responder for the "ai.chatbot@jnt.com" chat thread.
//
// Triggered by a Postgres AFTER INSERT trigger (see the accompanying migration)
// on public.request_chat_messages, scoped to rows where the recipient is the
// AI assistant and the sender is NOT the assistant itself (loop-safety).
//
// Deploy: supabase functions deploy ai-chat-assistant --project-ref <ref>
// Required secrets (set once per project):
//   supabase secrets set AI_ASSISTANT_WEBHOOK_SECRET=<random-string> --project-ref <ref>
// SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY are auto-injected by the platform.

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const AI_EMAIL = 'ai.chatbot@jnt.com';
const AI_NAME = 'JNT Assistant';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const WEBHOOK_SECRET = Deno.env.get('AI_ASSISTANT_WEBHOOK_SECRET') ?? '';

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { persistSession: false },
});

interface ChatMessageRow {
  id: string;
  conversation_id: string;
  request_id: string | null;
  client_email: string | null;
  artist_email: string | null;
  client_name: string | null;
  artist_name: string | null;
  sender_email: string | null;
  sender_name: string | null;
  text: string | null;
}

interface WebhookPayload {
  type: string;
  table: string;
  record: ChatMessageRow;
}

Deno.serve(async (req: Request) => {
  if (req.method !== 'POST') {
    return new Response('Method not allowed', { status: 405 });
  }

  if (WEBHOOK_SECRET) {
    const provided = req.headers.get('x-webhook-secret') ?? '';
    if (provided !== WEBHOOK_SECRET) {
      return new Response('Unauthorized', { status: 401 });
    }
  }

  let payload: WebhookPayload;
  try {
    payload = await req.json();
  } catch {
    return new Response('Invalid JSON', { status: 400 });
  }

  const message = payload.record;
  if (!message || payload.table !== 'request_chat_messages') {
    return new Response('Ignored', { status: 200 });
  }

  const senderEmail = normalizeEmail(message.sender_email);
  const artistEmail = normalizeEmail(message.artist_email);

  // Loop-safety: only respond to messages addressed to the assistant and
  // never generated by the assistant itself.
  if (artistEmail !== AI_EMAIL || senderEmail === AI_EMAIL) {
    return new Response('Ignored', { status: 200 });
  }

  try {
    const replyText = await buildReply(message);
    await sendAssistantReply(message, replyText);
    return new Response('OK', { status: 200 });
  } catch (error) {
    console.error('[ai-chat-assistant] failed:', error);
    // Don't fail the trigger loudly; the user's own message still landed.
    return new Response('Error handled', { status: 200 });
  }
});

function normalizeEmail(value: string | null | undefined): string {
  return (value ?? '').trim().toLowerCase();
}

// ---------------------------------------------------------------------------
// Intent detection
// ---------------------------------------------------------------------------

type Intent =
  | 'order_status'
  | 'payment'
  | 'shipping'
  | 'review'
  | 'tip'
  | 'support'
  | 'unknown';

const MENU_TEXT =
  'I can help with:\n\n' +
  '1. Check my order status\n' +
  '2. Payment help\n' +
  '3. Shipping or delivery update\n' +
  '4. Leave a review\n' +
  '5. Add a tip\n' +
  '6. Contact support\n\n' +
  'Reply with a number, or just ask in your own words.';

function detectIntent(rawText: string): Intent {
  const text = rawText.trim().toLowerCase();

  // Numbered quick-choice (button taps send just the digit in some flows).
  switch (text) {
    case '1':
      return 'order_status';
    case '2':
      return 'payment';
    case '3':
      return 'shipping';
    case '4':
      return 'review';
    case '5':
      return 'tip';
    case '6':
      return 'support';
  }

  // Exact quick-choice button text (matches the welcome menu verbatim).
  if (text === 'check my order status') return 'order_status';
  if (text === 'payment help') return 'payment';
  if (text === 'shipping or delivery update') return 'shipping';
  if (text === 'leave a review') return 'review';
  if (text === 'add a tip') return 'tip';
  if (text === 'contact support') return 'support';

  // Keyword fallback for free-text questions.
  if (/\b(order|request)\b.*\b(status|where|track)\b|\bstatus\b/.test(text)) {
    return 'order_status';
  }
  if (/\bpay(ment)?\b|\bcharge\b|\brefund\b|\binvoice\b/.test(text)) {
    return 'payment';
  }
  if (/\bship(ping|ped)?\b|\bdeliver(y|ed)?\b|\btrack(ing)?\b/.test(text)) {
    return 'shipping';
  }
  if (/\breview\b|\brate\b|\brating\b/.test(text)) {
    return 'review';
  }
  if (/\btip\b|\bgratuity\b/.test(text)) {
    return 'tip';
  }
  if (/\bsupport\b|\bhelp\b|\bhuman\b|\bagent\b|\bcontact\b/.test(text)) {
    return 'support';
  }

  return 'unknown';
}

// ---------------------------------------------------------------------------
// Reply generation
// ---------------------------------------------------------------------------

async function buildReply(message: ChatMessageRow): Promise<string> {
  const intent = detectIntent(message.text ?? '');
  const requestId = message.request_id;

  switch (intent) {
    case 'order_status':
      return await replyOrderStatus(requestId);
    case 'payment':
      return await replyPayment(requestId);
    case 'shipping':
      return await replyShipping(requestId);
    case 'review':
      return await replyReview(requestId, message.artist_name);
    case 'tip':
      return await replyTip(requestId);
    case 'support':
      return await replySupport(message);
    default:
      return MENU_TEXT;
  }
}

interface RequestRow {
  status: string | null;
  client_status: string | null;
  artist_status: string | null;
  order_number: string | null;
  accepted_by_artist_name: string | null;
  payment_status: string | null;
  payment_amount: number | null;
  currency: string | null;
  paid_at: string | null;
  shipping_status: string | null;
  tracking_number: string | null;
  shipped_at: string | null;
  delivered_at: string | null;
  cancelled_at: string | null;
  cancel_reason: string | null;
}

const REQUEST_COLUMNS =
  'status, client_status, artist_status, order_number, accepted_by_artist_name, ' +
  'payment_status, payment_amount, currency, paid_at, shipping_status, ' +
  'tracking_number, shipped_at, delivered_at, cancelled_at, cancel_reason';

async function fetchRequestRow(requestId: string | null): Promise<RequestRow | null> {
  if (!requestId) return null;

  const { data: clientRow } = await supabase
    .from('client_custom_requests')
    .select(REQUEST_COLUMNS)
    .eq('id', requestId)
    .maybeSingle();
  if (clientRow) return clientRow as RequestRow;

  const { data: companyRow } = await supabase
    .from('company_custom_requests')
    .select(REQUEST_COLUMNS)
    .eq('id', requestId)
    .maybeSingle();
  return (companyRow as RequestRow) ?? null;
}

async function replyOrderStatus(requestId: string | null): Promise<string> {
  const row = await fetchRequestRow(requestId);
  if (!row) {
    return "I couldn't find that order. Could you confirm the order number?";
  }

  if (row.cancelled_at) {
    const reason = row.cancel_reason?.trim();
    return (
      `Order ${row.order_number ?? ''} was cancelled` +
      (reason ? ` (reason: ${reason}).` : '.') +
      ' You can resubmit a new request any time from your orders page.'
    );
  }

  const status = row.status ?? 'pending';
  const artist = row.accepted_by_artist_name?.trim();
  const artistLine = artist
    ? `Your artist, ${artist}, is assigned.`
    : 'An artist has not been assigned yet.';

  return (
    `Order ${row.order_number ?? ''} status: ${humanize(status)}. ${artistLine}`
  );
}

async function replyPayment(requestId: string | null): Promise<string> {
  const row = await fetchRequestRow(requestId);
  if (!row) {
    return "I couldn't find payment details for that order. Could you confirm the order number?";
  }

  const status = row.payment_status?.trim();
  if (!status || status.toLowerCase() === 'pending') {
    return 'No payment has been made yet for this order. You can complete payment from the order details page.';
  }

  const amount = row.payment_amount;
  const currency = row.currency ?? 'USD';
  const paidAt = row.paid_at ? new Date(row.paid_at).toLocaleDateString() : null;
  const amountLine = amount != null ? ` of ${currency} ${amount}` : '';
  const dateLine = paidAt ? ` on ${paidAt}` : '';

  return `Payment status: ${humanize(status)}${amountLine}${dateLine}.`;
}

async function replyShipping(requestId: string | null): Promise<string> {
  const row = await fetchRequestRow(requestId);
  if (!row) {
    return "I couldn't find shipping details for that order. Could you confirm the order number?";
  }

  if (row.delivered_at) {
    return `Your order was delivered on ${new Date(row.delivered_at).toLocaleDateString()}.`;
  }

  if (row.shipped_at || row.tracking_number) {
    const trackingLine = row.tracking_number
      ? ` Tracking number: ${row.tracking_number}.`
      : '';
    const shippedLine = row.shipped_at
      ? ` Shipped on ${new Date(row.shipped_at).toLocaleDateString()}.`
      : '';
    return `Your order is on its way.${shippedLine}${trackingLine}`;
  }

  return 'Your order has not shipped yet. We will update tracking as soon as it ships.';
}

async function replyReview(requestId: string | null, artistName: string | null): Promise<string> {
  if (!requestId) {
    return "I couldn't find that order to check for a review.";
  }

  const { data } = await supabase
    .from('reviews')
    .select('rating')
    .eq('order_id', requestId)
    .maybeSingle();

  if (data) {
    return `You already left a ${data.rating}-star review for this order. Thank you!`;
  }

  const artist = artistName?.trim();
  return (
    `You haven't left a review yet${artist ? ` for ${artist}` : ''}. ` +
    'Once your order is delivered, you can leave a review from the order details page.'
  );
}

async function replyTip(requestId: string | null): Promise<string> {
  if (!requestId) {
    return "I couldn't find that order to check tip status.";
  }

  const { data } = await supabase
    .from('tips')
    .select('status, tip_amount')
    .eq('order_id', requestId)
    .maybeSingle();

  if (data) {
    return `You already added a tip of $${data.tip_amount} (${humanize(data.status)}).`;
  }

  return "You haven't added a tip for this order yet. You can add one from the order details page after delivery.";
}

async function replySupport(message: ChatMessageRow): Promise<string> {
  try {
    await supabase.from('admin_notifications').insert({
      type: 'ai_chat_support_request',
      source: 'request_chat_messages',
      request_id: message.request_id,
      title: 'Support requested via AI Assistant',
      message: `${message.client_name ?? message.client_email ?? 'A client'} asked for support: "${(message.text ?? '').slice(0, 300)}"`,
      date_label: new Date().toISOString(),
      event_at: new Date().toISOString(),
      payload: {
        conversationId: message.conversation_id,
        clientEmail: message.client_email,
      },
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    });
  } catch (error) {
    console.error('[ai-chat-assistant] failed to notify admins:', error);
  }

  return (
    "I've let our support team know you need help — someone will follow up here shortly. " +
    'In the meantime, tell me more about the issue and I can try to help right away.'
  );
}

function humanize(value: string): string {
  return value
    .trim()
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

// ---------------------------------------------------------------------------
// Sending the reply
// ---------------------------------------------------------------------------

async function sendAssistantReply(message: ChatMessageRow, text: string): Promise<void> {
  const nowIso = new Date().toISOString();

  await supabase.from('request_chat_messages').insert({
    conversation_id: message.conversation_id,
    request_id: message.request_id,
    client_email: message.client_email,
    artist_email: AI_EMAIL,
    client_name: message.client_name,
    artist_name: AI_NAME,
    sender_email: AI_EMAIL,
    sender_name: AI_NAME,
    text,
    attachment_url: '',
    attachment_type: '',
    attachment_name: '',
    created_at: nowIso,
    updated_at: nowIso,
  });

  await supabase
    .from('request_chats')
    .update({
      last_message: text,
      last_message_at: nowIso,
      last_sender_email: AI_EMAIL,
      last_sender_name: AI_NAME,
      updated_at: nowIso,
    })
    .eq('id', message.conversation_id);
}
