// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOOBVmN6Uil9-GIlvpQYLpWvBT3XGKZuQ',
    appId: '1:712519134055:web:0e8d690a743d8e471d1dc2',
    messagingSenderId: '712519134055',
    projectId: 'jnt-app-c3097',
    authDomain: 'jnt-app-c3097.firebaseapp.com',
    storageBucket: 'jnt-app-c3097.firebasestorage.app',
    measurementId: 'G-Y7KE4MQLYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgN51wb16qNh7DG1ZNuiK7Od8uuMdwgsU',
    appId: '1:712519134055:android:41279cb6f3f510041d1dc2',
    messagingSenderId: '712519134055',
    projectId: 'jnt-app-c3097',
    storageBucket: 'jnt-app-c3097.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrcSG6U4VXqiwtv8AJ0rUvBv8jrutX9Qc',
    appId: '1:712519134055:ios:5fe9b1d7107333501d1dc2',
    messagingSenderId: '712519134055',
    projectId: 'jnt-app-c3097',
    storageBucket: 'jnt-app-c3097.firebasestorage.app',
    iosBundleId: 'com.example.jntApp0120',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrcSG6U4VXqiwtv8AJ0rUvBv8jrutX9Qc',
    appId: '1:712519134055:ios:5fe9b1d7107333501d1dc2',
    messagingSenderId: '712519134055',
    projectId: 'jnt-app-c3097',
    storageBucket: 'jnt-app-c3097.firebasestorage.app',
    iosBundleId: 'com.example.jntApp0120',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOOBVmN6Uil9-GIlvpQYLpWvBT3XGKZuQ',
    appId: '1:712519134055:web:9783d5528baec3da1d1dc2',
    messagingSenderId: '712519134055',
    projectId: 'jnt-app-c3097',
    authDomain: 'jnt-app-c3097.firebaseapp.com',
    storageBucket: 'jnt-app-c3097.firebasestorage.app',
    measurementId: 'G-LJLR7EHBWG',
  );

}